// Smart Finance App - Main Application
// Free APIs: OpenRouter, Inflation Data, News

// Configuration
const CONFIG = {
    GITHUB_REPO: 'YOUR_USERNAME/YOUR_REPO', // User will set this
    DATA_URL: './data/latest.json',
    UPDATE_INTERVAL: 3600000, // 1 hour
};

// State Management
const state = {
    currentView: 'dashboard',
    userData: null,
    loans: [],
    inflationData: null,
    newsData: null,
    aiInsights: null,
    lastUpdate: null
};

// Initialize App
document.addEventListener('DOMContentLoaded', async () => {
    console.log('Initializing Smart Finance App...');

    // Load user data from localStorage
    loadUserData();

    // Setup event listeners
    setupEventListeners();

    // Load data
    await loadData();

    // Hide loading screen
    setTimeout(() => {
        document.getElementById('loading-screen').classList.add('hidden');
        document.getElementById('main-app').classList.remove('hidden');
    }, 1000);

    // Setup auto-refresh
    setInterval(loadData, CONFIG.UPDATE_INTERVAL);
});

// Load User Data
function loadUserData() {
    const saved = localStorage.getItem('smartFinanceUser');
    if (saved) {
        state.userData = JSON.parse(saved);
    } else {
        // Initialize new user
        state.userData = {
            id: generateId(),
            salary: 0,
            yearlyRaise: 0,
            currency: 'SAR',
            createdAt: new Date().toISOString()
        };
        saveUserData();
    }

    // Load loans
    const savedLoans = localStorage.getItem('smartFinanceLoans');
    if (savedLoans) {
        state.loans = JSON.parse(savedLoans);
    }
}

function saveUserData() {
    localStorage.setItem('smartFinanceUser', JSON.stringify(state.userData));
}

function saveLoans() {
    localStorage.setItem('smartFinanceLoans', JSON.stringify(state.loans));
}

// Load Data from GitHub Actions generated JSON
async function loadData() {
    try {
        // Try to fetch the latest data generated by GitHub Actions
        const response = await fetch(CONFIG.DATA_URL + '?t=' + Date.now());

        if (response.ok) {
            const data = await response.json();
            state.inflationData = data.inflation;
            state.newsData = data.news;
            state.aiInsights = data.insights;
            state.lastUpdate = data.timestamp;

            // Update UI
            updateDashboard();
            updateNewsSection();
            updateInsightsSection();
        } else {
            // If no data yet, use placeholder
            console.log('No data available yet, using placeholders');
            usePlaceholderData();
        }
    } catch (error) {
        console.error('Error loading data:', error);
        usePlaceholderData();
    }
}

function usePlaceholderData() {
    state.inflationData = { current: 0, change: 0 };
    state.newsData = [];
    state.aiInsights = { summary: 'Waiting for AI insights. GitHub Actions will update this daily.' };
    updateDashboard();
    updateNewsSection();
    updateInsightsSection();
}

// Update Dashboard
function updateDashboard() {
    // Update inflation stat
    if (state.inflationData) {
        document.getElementById('current-inflation').textContent =
            `${state.inflationData.current.toFixed(2)}%`;

        const changeEl = document.getElementById('inflation-change');
        const change = state.inflationData.change || 0;
        changeEl.textContent = `${change >= 0 ? '+' : ''}${change.toFixed(2)}% from last month`;
        changeEl.className = `stat-change ${change >= 0 ? 'positive' : 'negative'}`;
    }

    // Update loans stat
    document.getElementById('total-loans').textContent = state.loans.length;
    const totalAmount = state.loans.reduce((sum, loan) => sum + loan.amount, 0);
    document.getElementById('loans-detail').textContent =
        `Total: ${formatCurrency(totalAmount)}`;

    // Calculate purchasing power loss
    if (state.userData.salary > 0 && state.inflationData) {
        const monthlyLoss = (state.userData.salary * state.inflationData.current) / 100 / 12;
        document.getElementById('power-loss').textContent = formatCurrency(monthlyLoss);
        document.getElementById('power-loss-detail').textContent = 'Per month';
    }

    // Next payment
    if (state.loans.length > 0) {
        const nextLoan = state.loans[0];
        document.getElementById('next-payment').textContent = formatCurrency(nextLoan.monthlyPayment);
        document.getElementById('next-payment-detail').textContent = `${nextLoan.type} - ${nextLoan.duration} months`;
    }

    // Last update time
    if (state.lastUpdate) {
        document.getElementById('last-update-time').textContent =
            new Date(state.lastUpdate).toLocaleString('ar-SA');
    }
}

// Update News Section
function updateNewsSection() {
    const container = document.getElementById('news-container');

    if (!state.newsData || state.newsData.length === 0) {
        container.innerHTML = '<div class="loading-placeholder">No news available yet. Daily updates coming soon!</div>';
        return;
    }

    container.innerHTML = state.newsData.map(article => `
        <div class="news-card" onclick="window.open('${article.url}', '_blank')">
            <div class="news-source">${article.source}</div>
            <div class="news-title">${article.title}</div>
            <div class="news-description">${article.description || ''}</div>
            <div class="news-time">${new Date(article.publishedAt).toLocaleDateString('ar-SA')}</div>
        </div>
    `).join('');
}

// Update Insights Section
function updateInsightsSection() {
    const container = document.getElementById('ai-insights-container');
    const fullContainer = document.getElementById('full-insights-container');

    if (!state.aiInsights || !state.aiInsights.summary) {
        const placeholder = '<div class="loading-placeholder">جاري توليد الرؤى الذكية...</div>';
        container.innerHTML = placeholder;
        fullContainer.innerHTML = placeholder;
        return;
    }

    // Parse simple markdown (bold and newlines)
    const formatText = (text) => {
        return text
            .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>') // Bold
            .replace(/\n/g, '<br>'); // Newlines
    };

    const formattedSummary = formatText(state.aiInsights.summary);

    // Dashboard preview (Show all of it, it's concise now)
    const content = `
        <div class="insight-item smart-insight">
            <div class="insight-content">${formattedSummary}</div>
        </div>
    `;

    container.innerHTML = content;
    fullContainer.innerHTML = content;
}

// Event Listeners
function setupEventListeners() {
    // Navigation
    document.querySelectorAll('.nav-link').forEach(link => {
        link.addEventListener('click', (e) => {
            const view = e.target.dataset.view;
            switchView(view);
        });
    });

    // Add loan button
    document.getElementById('add-loan-btn')?.addEventListener('click', () => {
        document.getElementById('loan-modal').classList.remove('hidden');
    });

    // Close modal
    document.querySelectorAll('.close-modal').forEach(btn => {
        btn.addEventListener('click', () => {
            document.getElementById('loan-modal').classList.add('hidden');
        });
    });

    // Save loan
    document.getElementById('save-loan')?.addEventListener('click', saveLoan);

    // Save settings
    document.getElementById('save-settings')?.addEventListener('click', saveSettings);

    // Generate QR code
    generateQRCode();

    // Load settings into form
    if (state.userData) {
        document.getElementById('salary-input').value = state.userData.salary || '';
        document.getElementById('raise-input').value = state.userData.yearlyRaise || '';
        document.getElementById('currency-select').value = state.userData.currency || 'SAR';
    }
}

// Switch View
function switchView(viewName) {
    // Update nav
    document.querySelectorAll('.nav-link').forEach(link => {
        link.classList.remove('active');
        if (link.dataset.view === viewName) {
            link.classList.add('active');
        }
    });

    // Update views
    document.querySelectorAll('.view').forEach(view => {
        view.classList.remove('active');
    });
    document.getElementById(`${viewName}-view`).classList.add('active');

    // Load view-specific data
    if (viewName === 'loans') {
        renderLoans();
    }
}

// Render Loans
function renderLoans() {
    const container = document.getElementById('loans-container');

    if (state.loans.length === 0) {
        container.innerHTML = `
            <div class="empty-state">
                <svg width="64" height="64" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-6h2v6zm0-8h-2V7h2v2z"/>
                </svg>
                <h3>No loans yet</h3>
                <p>Start by adding your first loan to track its real cost</p>
            </div>
        `;
        return;
    }

    container.innerHTML = state.loans.map((loan, index) => {
        const progress = calculateLoanProgress(loan);
        const inflationImpact = calculateInflationImpact(loan);

        return `
            <div class="loan-card">
                <div class="loan-header">
                    <div class="loan-type">${getLoanTypeLabel(loan.type)}</div>
                    <div class="loan-amount">${formatCurrency(loan.amount)}</div>
                </div>
                <div class="loan-details">
                    <div class="loan-detail-row">
                        <span>Monthly Payment:</span>
                        <strong>${formatCurrency(loan.monthlyPayment)}</strong>
                    </div>
                    <div class="loan-detail-row">
                        <span>Duration:</span>
                        <strong>${loan.duration} months</strong>
                    </div>
                    <div class="loan-detail-row">
                        <span>Interest Rate:</span>
                        <strong>${loan.interestRate}%</strong>
                    </div>
                    <div class="loan-detail-row">
                        <span>% of Income:</span>
                        <strong>${loan.percentageOfIncome}%</strong>
                    </div>
                    <div class="loan-detail-row">
                        <span>Inflation Impact:</span>
                        <strong class="negative">${formatCurrency(inflationImpact)}</strong>
                    </div>
                </div>
                <div class="progress-bar">
                    <div class="progress-fill" style="width: ${progress}%"></div>
                </div>
            </div>
        `;
    }).join('');
}

// Save Loan
function saveLoan() {
    const loan = {
        id: generateId(),
        type: document.getElementById('loan-type').value,
        amount: parseFloat(document.getElementById('loan-amount').value),
        interestRate: parseFloat(document.getElementById('loan-interest').value),
        duration: parseInt(document.getElementById('loan-duration').value),
        monthlyPayment: parseFloat(document.getElementById('loan-payment').value),
        percentageOfIncome: parseFloat(document.getElementById('loan-percentage').value),
        createdAt: new Date().toISOString()
    };

    state.loans.push(loan);
    saveLoans();

    // Close modal and update UI
    document.getElementById('loan-modal').classList.add('hidden');
    renderLoans();
    updateDashboard();

    // Clear form
    document.getElementById('loan-type').value = 'car';
    document.getElementById('loan-amount').value = '';
    document.getElementById('loan-interest').value = '';
    document.getElementById('loan-duration').value = '';
    document.getElementById('loan-payment').value = '';
    document.getElementById('loan-percentage').value = '';
}

// Save Settings
function saveSettings() {
    state.userData.salary = parseFloat(document.getElementById('salary-input').value) || 0;
    state.userData.yearlyRaise = parseFloat(document.getElementById('raise-input').value) || 0;
    state.userData.currency = document.getElementById('currency-select').value;

    saveUserData();
    updateDashboard();

    alert('Settings saved successfully!');
}

// Generate QR Code
function generateQRCode() {
    const qrContainer = document.getElementById('qr-code');
    const data = JSON.stringify({
        userId: state.userData.id,
        type: 'smartfinance'
    });

    // Use a simple QR code representation (in production, use a library like qrcode.js)
    qrContainer.innerHTML = `
        <div style="width: 200px; height: 200px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); display: flex; align-items: center; justify-content: center; border-radius: 12px;">
            <div style="background: white; padding: 10px; border-radius: 8px;">
                <p style="color: black; font-size: 12px; margin: 0;">User ID:<br/>${state.userData.id.substring(0, 12)}</p>
            </div>
        </div>
    `;
}

// Utility Functions
function generateId() {
    return Date.now().toString(36) + Math.random().toString(36).substr(2);
}

function formatCurrency(amount) {
    const currency = state.userData?.currency || 'SAR';
    return new Intl.NumberFormat('ar-SA', {
        style: 'currency',
        currency: currency
    }).format(amount);
}

function getLoanTypeLabel(type) {
    const labels = {
        car: 'Car Loan',
        rent: 'Rent',
        installment: 'Installment',
        bnpl: 'Buy Now Pay Later',
        custom: 'Custom'
    };
    return labels[type] || type;
}

function calculateLoanProgress(loan) {
    const monthsSinceStart = Math.floor(
        (new Date() - new Date(loan.createdAt)) / (1000 * 60 * 60 * 24 * 30)
    );
    return Math.min((monthsSinceStart / loan.duration) * 100, 100);
}

function calculateInflationImpact(loan) {
    if (!state.inflationData) return 0;

    const totalPaid = loan.monthlyPayment * loan.duration;
    const inflationRate = state.inflationData.current / 100;
    const years = loan.duration / 12;
    const realValue = totalPaid / Math.pow(1 + inflationRate, years);

    return totalPaid - realValue;
}

// Service Worker Registration
if ('serviceWorker' in navigator) {
    window.addEventListener('load', () => {
        navigator.serviceWorker.register('./sw.js')
            .then(reg => console.log('Service Worker registered'))
            .catch(err => console.log('Service Worker registration failed'));
    });
}
